### ISSUE TITLE
installation instruction

### ISSUE THREAD

**Issue by yassinebha** [robb-brown/IntroToDeepLearning#1]
In the installation, the step three doesn't work.
``` Directory 'tfs' is not installable. File 'setup.py' not found.``` 

I'm using ubuntu 16.04
Thanks

**Comment by robb-brown** [comment]
Hi,
Thanks for spotting this.  You can either type "pip install ." in the copy you've got, or pull the latest update from git and use "pip install tfs" as per the instructions.
